"""
Document Loader module for the Multi-RAG system.
Responsible for loading various document types from the knowledge base directories.
"""

import logging
from pathlib import Path
from typing import List, Dict

from langchain_core.documents import Document
from langchain_community.document_loaders import (
    TextLoader,
    UnstructuredMarkdownLoader,
    CSVLoader,
    PyPDFLoader,
)
from langchain_community.document_loaders.base import BaseLoader

# Configure module-level logger
logger = logging.getLogger(__name__)
if not logger.hasHandlers():
    handler = logging.StreamHandler()
    formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.setLevel(logging.INFO)


class DocumentLoader:
    """
    A unified document loader for the Multi-RAG Marketing Intelligence Platform.
    Loads reports generated by the MMM, Sales Forecasting, and Sentiment modules.
    Supports both flat directory structures and domain-specific subfolders.
    """

    SUPPORTED_EXTENSIONS = {
        ".txt": TextLoader,
        ".md": UnstructuredMarkdownLoader,
        ".csv": CSVLoader,
        ".pdf": PyPDFLoader,
    }

    def __init__(self, base_path: str | Path) -> None:
        """
        Initialize the DocumentLoader.

        Args:
            base_path: The project root directory or the specific reports directory.
                       The loader will automatically resolve the 'reports' folder.
        """
        base_path = Path(base_path)
        if (base_path / "reports").is_dir():
            self.reports_directory = base_path / "reports"
        else:
            self.reports_directory = base_path

        self._detect_architecture()

    def _detect_architecture(self) -> None:
        """Determines if the reports directory is flat or contains domain subfolders."""
        domains = ["mmm", "forecast", "sentiment"]
        self.is_domain_architecture = any((self.reports_directory / d).is_dir() for d in domains)
        if self.is_domain_architecture:
            logger.info("Found domain-folder architecture.")
        else:
            logger.info("Found flat report architecture.")

    def _infer_domain(self, filename: str) -> str:
        """
        Infers the knowledge domain based on the filename.

        Args:
            filename: The name of the file to inspect.

        Returns:
            The inferred domain string.
        """
        lower_name = filename.lower()
        if "forecast" in lower_name:
            return "forecast"
        elif "sentiment" in lower_name:
            return "sentiment"
        elif any(kw in lower_name for kw in ["insight", "recommendation", "understanding", "mmm"]):
            return "mmm"
        return "general"

    def _load_file(self, file_path: Path, domain: str) -> List[Document]:
        """Loads a single file and enriches its metadata."""
        extension = file_path.suffix.lower()
        if extension not in self.SUPPORTED_EXTENSIONS:
            logger.debug(f"Unsupported file type '{extension}' for file: {file_path.name}")
            return []

        logger.info(f"Loading {file_path.name}")
        loader_class = self.SUPPORTED_EXTENSIONS[extension]
        
        try:
            loader: BaseLoader = loader_class(str(file_path))
            docs = loader.load()

            for doc in docs:
                doc.metadata.update({
                    "source": str(file_path.absolute()),
                    "filename": file_path.name,
                    "extension": extension,
                    "knowledge_domain": domain,
                    "relative_path": str(file_path.relative_to(self.reports_directory)),
                    # Providing additional metadata exactly as requested
                    "file_name": file_path.name,
                    "file_type": extension,
                    "domain": domain
                })
            return docs
        except PermissionError:
            logger.warning(f"Permission denied: cannot read '{file_path.name}'.")
            return []
        except Exception as e:
            logger.warning(f"Failed to load file '{file_path.name}'. Error: {e}")
            return []

    def _load_flat_documents(self) -> Dict[str, List[Document]]:
        """
        Loads all supported documents directly inside reports/ 
        and groups them by inferred domain.
        """
        if not self.reports_directory.exists() or not self.reports_directory.is_dir():
            logger.warning(f"Reports directory does not exist or is not a directory at {self.reports_directory}.")
            return {}

        grouped_docs: Dict[str, List[Document]] = {}
        files_discovered = 0
        files_loaded = 0

        for file_path in self.reports_directory.iterdir():
            if not file_path.is_file():
                continue

            files_discovered += 1
            domain = self._infer_domain(file_path.name)
            docs = self._load_file(file_path, domain)
            
            if docs:
                if domain not in grouped_docs:
                    grouped_docs[domain] = []
                grouped_docs[domain].extend(docs)
                files_loaded += 1

        logger.info(f"Discovered {files_discovered} files in flat directory.")
        logger.info(f"Loaded {files_loaded} files successfully.")
        
        return grouped_docs

    def _load_documents_from_domain(self, domain: str) -> List[Document]:
        """
        Loads all supported documents from a specific domain subdirectory.
        """
        domain_path = self.reports_directory / domain
        loaded_documents: List[Document] = []

        if not domain_path.exists() or not domain_path.is_dir():
            logger.warning(f"Domain folder '{domain}' does not exist at {domain_path}. Returning empty list.")
            return loaded_documents

        files_discovered = 0
        files_loaded = 0

        for file_path in domain_path.rglob("*"):
            if not file_path.is_file():
                continue

            files_discovered += 1
            docs = self._load_file(file_path, domain)
            
            if docs:
                loaded_documents.extend(docs)
                files_loaded += 1

        logger.info(
            f"Domain '{domain}': Discovered {files_discovered} files | "
            f"Loaded {files_loaded} files"
        )

        return loaded_documents

    def load_mmm_documents(self) -> List[Document]:
        """Loads every supported document for the MMM domain."""
        logger.info("Starting document load for MMM domain...")
        if self.is_domain_architecture:
            return self._load_documents_from_domain("mmm")
        else:
            return self._load_flat_documents().get("mmm", [])

    def load_forecast_documents(self) -> List[Document]:
        """Loads every supported document for the Forecast domain."""
        logger.info("Starting document load for Forecast domain...")
        if self.is_domain_architecture:
            return self._load_documents_from_domain("forecast")
        else:
            return self._load_flat_documents().get("forecast", [])

    def load_sentiment_documents(self) -> List[Document]:
        """Loads every supported document for the Sentiment domain."""
        logger.info("Starting document load for Sentiment domain...")
        if self.is_domain_architecture:
            return self._load_documents_from_domain("sentiment")
        else:
            return self._load_flat_documents().get("sentiment", [])

    def load_all_documents(self) -> Dict[str, List[Document]]:
        """
        Loads every supported report from all knowledge domains.
        """
        logger.info("Initiating full document load across all domains...")
        
        if self.is_domain_architecture:
            all_docs = {
                "mmm": self.load_mmm_documents(),
                "forecast": self.load_forecast_documents(),
                "sentiment": self.load_sentiment_documents()
            }
        else:
            all_docs = self._load_flat_documents()
            # Ensure standard keys exist to prevent KeyErrors down the line
            for d in ["mmm", "forecast", "sentiment"]:
                if d not in all_docs:
                    all_docs[d] = []
        
        total_loaded = sum(len(docs) for docs in all_docs.values())
        logger.info(f"Loaded {total_loaded} documents.")
        logger.info(f"Total Documents Loaded = {total_loaded}")
        
        return all_docs
